<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Institute;
use App\Models\User;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class InstituteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $institutes = [
            [
                'institute_name' => 'Elite Academy',
                'description' => 'Premier coaching institute for competitive exam preparation with over 15 years of experience.',
                'registration_number' => 'ELT2008001',
                'website' => 'https://eliteacademy.edu',
                'contact_person' => 'Dr. Ramesh Gupta',
                'contact_phone' => '+91-9876543210',
                'address' => '123 Education Street, Knowledge City',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'pincode' => '400001',
                'established_year' => 2008,
                'total_students' => 1200,
                'rating' => 4.5,
                'verified' => true,
                'facilities' => json_encode(['Library', 'Computer Lab', 'Science Lab', 'Auditorium', 'Sports Complex']),
                'gallery_images' => json_encode(['elite1.jpg', 'elite2.jpg', 'elite3.jpg']),
                'user_email' => 'admin@eliteacademy.edu',
                'user_name' => 'Elite Academy Admin',
            ],
            [
                'institute_name' => 'Success Point Institute',
                'description' => 'Specialized coaching for JEE, NEET, and other competitive examinations.',
                'registration_number' => 'SUC2012002',
                'website' => 'https://successpoint.com',
                'contact_person' => 'Prof. Anjali Sharma',
                'contact_phone' => '+91-9876543211',
                'address' => '456 Learning Lane, Education Hub',
                'city' => 'Delhi',
                'state' => 'Delhi',
                'pincode' => '110001',
                'established_year' => 2012,
                'total_students' => 800,
                'rating' => 4.3,
                'verified' => true,
                'facilities' => json_encode(['Digital Classrooms', 'Library', 'Test Series Hall', 'Cafeteria']),
                'gallery_images' => json_encode(['success1.jpg', 'success2.jpg']),
                'user_email' => 'admin@successpoint.com',
                'user_name' => 'Success Point Admin',
            ],
            [
                'institute_name' => 'Bright Future School',
                'description' => 'CBSE affiliated school providing quality education from kindergarten to grade 12.',
                'registration_number' => 'BFS1995003',
                'website' => 'https://brightfuture.edu.in',
                'contact_person' => 'Mrs. Priya Nair',
                'contact_phone' => '+91-9876543212',
                'address' => '789 Scholar Avenue, Academic District',
                'city' => 'Bangalore',
                'state' => 'Karnataka',
                'pincode' => '560001',
                'established_year' => 1995,
                'total_students' => 2500,
                'rating' => 4.7,
                'verified' => true,
                'facilities' => json_encode(['Swimming Pool', 'Basketball Court', 'Science Labs', 'Music Room', 'Art Studio']),
                'gallery_images' => json_encode(['bright1.jpg', 'bright2.jpg', 'bright3.jpg', 'bright4.jpg']),
                'user_email' => 'principal@brightfuture.edu.in',
                'user_name' => 'Bright Future Principal',
            ],
            [
                'institute_name' => 'Knowledge University',
                'description' => 'State university offering undergraduate and postgraduate programs in various disciplines.',
                'registration_number' => 'KNU1980004',
                'website' => 'https://knowledge.ac.in',
                'contact_person' => 'Dr. Vikram Singh',
                'contact_phone' => '+91-9876543213',
                'address' => '321 University Road, Campus City',
                'city' => 'Pune',
                'state' => 'Maharashtra',
                'pincode' => '411001',
                'established_year' => 1980,
                'total_students' => 15000,
                'rating' => 4.6,
                'verified' => true,
                'facilities' => json_encode(['Central Library', 'Research Centers', 'Hostels', 'Medical Center', 'Placement Cell']),
                'gallery_images' => json_encode(['knowledge1.jpg', 'knowledge2.jpg', 'knowledge3.jpg']),
                'user_email' => 'registrar@knowledge.ac.in',
                'user_name' => 'Knowledge University Registrar',
            ],
            [
                'institute_name' => 'Tech Skills Institute',
                'description' => 'Professional training institute for IT and software development courses.',
                'registration_number' => 'TSI2015005',
                'website' => 'https://techskills.co.in',
                'contact_person' => 'Mr. Arjun Reddy',
                'contact_phone' => '+91-9876543214',
                'address' => '654 Innovation Street, Tech Park',
                'city' => 'Hyderabad',
                'state' => 'Telangana',
                'pincode' => '500001',
                'established_year' => 2015,
                'total_students' => 500,
                'rating' => 4.4,
                'verified' => true,
                'facilities' => json_encode(['Computer Labs', 'Server Room', 'Conference Hall', 'Coding Bootcamp Area']),
                'gallery_images' => json_encode(['tech1.jpg', 'tech2.jpg']),
                'user_email' => 'admin@techskills.co.in',
                'user_name' => 'Tech Skills Admin',
            ],
            [
                'institute_name' => 'Global Learning Center',
                'description' => 'International coaching center for IELTS, TOEFL, SAT, and other global examinations.',
                'registration_number' => 'GLC2010006',
                'website' => 'https://globallearning.org',
                'contact_person' => 'Ms. Kavitha Menon',
                'contact_phone' => '+91-9876543215',
                'address' => '987 International Avenue, Global District',
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'pincode' => '600001',
                'established_year' => 2010,
                'total_students' => 300,
                'rating' => 4.8,
                'verified' => true,
                'facilities' => json_encode(['Language Labs', 'Mock Test Center', 'Resource Library', 'Counseling Room']),
                'gallery_images' => json_encode(['global1.jpg', 'global2.jpg']),
                'user_email' => 'director@globallearning.org',
                'user_name' => 'Global Learning Director',
            ],
            [
                'institute_name' => 'Creative Arts Academy',
                'description' => 'Specialized college for fine arts, music, and creative design programs.',
                'registration_number' => 'CAA2005007',
                'website' => 'https://creativearts.edu',
                'contact_person' => 'Prof. Ravi Varma',
                'contact_phone' => '+91-9876543216',
                'address' => '147 Artist Lane, Cultural Quarter',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'pincode' => '700001',
                'established_year' => 2005,
                'total_students' => 400,
                'rating' => 4.2,
                'verified' => true,
                'facilities' => json_encode(['Art Studios', 'Music Rooms', 'Performance Hall', 'Gallery', 'Workshop Areas']),
                'gallery_images' => json_encode(['creative1.jpg', 'creative2.jpg', 'creative3.jpg']),
                'user_email' => 'dean@creativearts.edu',
                'user_name' => 'Creative Arts Dean',
            ],
        ];

        foreach ($institutes as $institute) {
            // First create the user for the institute
            $user = User::create([
                'name' => $institute['user_name'],
                'email' => $institute['user_email'],
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'role' => 'institute',
                'phone' => $institute['contact_phone'],
                'address' => $institute['address'],
                'city' => $institute['city'],
                'state' => $institute['state'],
                'pincode' => $institute['pincode'],
                'country' => 'India',
                'is_active' => true,
                'remember_token' => Str::random(10),
            ]);

            // Then create the institute with the user_id
            Institute::create([
                'user_id' => $user->id,
                'institute_name' => $institute['institute_name'],
                'description' => $institute['description'],
                'registration_number' => $institute['registration_number'],
                'website' => $institute['website'],
                'contact_person' => $institute['contact_person'],
                'contact_phone' => $institute['contact_phone'],
                'address' => $institute['address'],
                'city' => $institute['city'],
                'state' => $institute['state'],
                'pincode' => $institute['pincode'],
                'established_year' => $institute['established_year'],
                'total_students' => $institute['total_students'],
                'rating' => $institute['rating'],
                'verified' => $institute['verified'],
                'facilities' => $institute['facilities'],
                'gallery_images' => $institute['gallery_images'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
